### ISSUE TITLE
User Guide - Add perl-XML-Simple dependancie

### ISSUE THREAD

**Issue by Zekyel** [centreon/centreon-plugins#1081]
Hello everybody,

I use Centreon Plugins to monitor ILO servers. I noticed an error when I using it.

_./centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --help
UNKNOWN: Cannot load module --custommode_
Can't locate XML/Simple.pm in @INC (@INC contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 27.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 27.
Compilation failed in require at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221.

I was able to solve this problem by installing the perl-XML-Simple module. This is not marked in the prerequisites to use Centreon Plugins in the user guide ( centreon-plugins/docs/fr/user/guide.rst).

Perhaps it would be interesting to add this module to the guide.

Best regards,
Aurélien

**Comment by cgagnaire** [comment]
Hi @Zekyel,
Thanks for using it!
The perl dependencies listed in the documentation are the most commonly used by the project. Not all dependencies are listed.
So that's why you may need some from time to time. If it's the case just do a `yum install 'perl(My::Dependency)'` and you're good to go.
In the other hand, we do manage dependencies in the packaged versions of the plugins in the Centreon standard repository. You should take a look.
