### ISSUE TITLE
invalid performance data

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1117]
## Bug

I am using the centreon plugins for checking a pfsense. the performance data is not given as defined in the monitoring developement guidelines and so, it is dropped as invalid in the Icinga2 InfluxDB writer.

[2018-08-30 13:52:51 +0200] warning/InfluxdbWriter: Ignoring invalid perfdata value: traffic_in_pass_em0.2507=1838511.47b/s;;;0;

See: https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

**Comment by Sims24** [comment]
Hi @MarcusCaepio 

I assume that the b/s is the issue here, am I right ? You may want to check the --filter-uom option to fix this parsing. e.g --filter-uom='B/s' should fix this error. 

Guidelines are prelly old, and do not cover so many uom. At this point we prefer to clearly show that's a per sec value as it provides an extra information. 

We do not have this issue with centreon-stream-connector when forwarding to influxdb storage which catch prelly well this format. Recommend you to also open an issue to Icinga guys wondering if their parser has any chance to manage this kind of UOM.

Regards,

**Comment by MarcusCaepio** [comment]
That helps, thank you
