### ISSUE TITLE
centreon_plugins.pl --list-plugin empty output

### ISSUE THREAD

**Issue by nicutor** [centreon/centreon-plugins#1250]
I am trying to use this command but it returns nothing: 
```
perl /usr/lib/nagios/plugins/centreon_plugins.pl --list-plugin
```
 --help options returns the help, but the --list-plugin is empty, how can I fix this?
```
# perl /usr/lib/nagios/plugins/centreon_plugins.pl --version
Global Version: 20170120
```
```
# perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --help
UNKNOWN: Cannot load module --plugin.
Can't locate os/linux/snmp/plugin.pm in @INC (@INC contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/vendor_perl/centreon/plugins/misc.pm line 221.
```

**Comment by CPbN** [comment]
Are you sure you downloaded / extracted the whole [Centreon Plugins package](https://github.com/centreon/centreon-plugins/releases) (the .zip or .tar.gz file) before running your command ?

**Comment by nicutor** [comment]
Hi @CPbN,

Everything was installed automatically by centreon packages. I followed the installation process from https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html
```
# rpm -qa | grep centreon-plugin- | wc -l
283
# find /usr/lib/centreon/plugins | wc -l
284

# rpm -qa | grep centreon-plugins
centreon-plugins-base-1.18-2.el7.centos.noarch
# rpm -ql centreon-plugins-base
/usr/lib/nagios/plugins/centreon_plugins.pl
/usr/share/perl5/vendor_perl/centreon/plugins
/usr/share/perl5/vendor_perl/centreon/plugins/alternative
/usr/share/perl5/vendor_perl/centreon/plugins/alternative/Getopt.pm
/usr/share/perl5/vendor_perl/centreon/plugins/misc.pm
/usr/share/perl5/vendor_perl/centreon/plugins/mode.pm
/usr/share/perl5/vendor_perl/centreon/plugins/options.pm
/usr/share/perl5/vendor_perl/centreon/plugins/output.pm
/usr/share/perl5/vendor_perl/centreon/plugins/perfdata.pm
/usr/share/perl5/vendor_perl/centreon/plugins/script.pm
/usr/share/perl5/vendor_perl/centreon/plugins/script_custom.pm
/usr/share/perl5/vendor_perl/centreon/plugins/script_simple.pm
/usr/share/perl5/vendor_perl/centreon/plugins/statefile.pm
/usr/share/perl5/vendor_perl/centreon/plugins/templates
/usr/share/perl5/vendor_perl/centreon/plugins/templates/counter.pm
/usr/share/perl5/vendor_perl/centreon/plugins/templates/hardware.pm
/usr/share/perl5/vendor_perl/centreon/plugins/values.pm
```
Is there any extra package that I need to install so I ca make this to work?

If I clone from github, seems to work, but, I need this to be done from packages.
Is there something that I am missing?
Should I always go on /usr/lib/nagios/plugins and clone the git project there in order to make this to work? What about the RPMs what install all of these plugins on /usr/lib/centreon/plugins?

The RPMs have the last version. 18.10.

**Comment by CPbN** [comment]
If you use the RPMs, I'm pretty sure `centreon-plugins-base` can be removed.
The plugins installed in `/usr/lib/centreon/plugins/` are the ones from `centreon-plugin-*` packages, and these `.pl` files can be executed directly, these are the individual fapack versions of the plugins.

You could also clone the git project, for example into `/usr/lib/centreon/plugins/git/`, so that you are sure to get the last modifications as soon as they reach the repository.

**Comment by Sims24** [comment]
Hi, 

@CPbN is right when advises you to use plugins under `/usr/lib/centreon/plugins/`. 

Nevertheless, few important things, you should not clone the git under under /usr/lib/centreon/plugins/` or a sub-directory because it might mess up some library and dependencies. 

Prefer to keep centreon-pluginst-base as it comes as a dependency from centreon itself if I remember well.

**Comment by nicutor** [comment]
Thank you!
