### ISSUE TITLE
Centreon Plugin - Check Cisco Stack (CISCO-STACKWISE-MIB).

### ISSUE THREAD

**Issue by amitsamy** [centreon/centreon-plugins#1487]
Hello Team,

I have a Cisco Stack switch (C3750) with stack mode activated and there are 4 members.
In normal operation, the output is as follows:
/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=stack --hostname=10.6.30.133 --snmp-version='2c' --snmp-community='nicoll'  --verbose --critical-ready=4:4 --critical-status='%{state} =!~ /ready/' --opt-exit='CRITICAL' --debug
OK: Number of members Waiting: 0, Progressing: 0, Added: 0, Ready: 4, SDM Mismatch: 0, Version Mismatch: 0, Feature Mismatch: 0, New Master Init: 0, Provisioned: 0, Invalid: 0, Removed: 0 - All stack members status are ok | 'waiting'=0;;;0; 'progressing'=0;;;0; 'added'=0;;;0; 'ready'=4;;4:4;0; 'sdm_mismatch'=0;;;0; 'version_mismatch'=0;;;0; 'feature_mismatch'=0;;;0; 'new_master_init'=0;;;0; 'provisioned'=0;;;0; 'invalid'=0;;;0; 'removed'=0;;;0;
Member '1' State is 'ready', Role is 'master'
Member '2' State is 'ready', Role is 'member'
Member '3' State is 'ready', Role is 'member'
Member '4' State is 'ready', Role is 'member'

Below are the options:
Mode:
    Check Cisco Stack (CISCO-STACKWISE-MIB).

    --warning-*
            Set warning threshold on members count for each states. (Can be:
            'waiting', 'progressing', 'added', 'ready', 'sdm-mismatch',
            'version-mismatch', 'feature-mismatch', 'new-master-init',
            'provisioned', 'invalid', 'removed')

    --critical-*
            Set warning threshold on members count for each states. (Can be:
            'waiting', 'progressing', 'added', 'ready', 'sdm-mismatch',
            'version-mismatch', 'feature-mismatch', 'new-master-init',
            'provisioned', 'invalid', 'removed')

    --warning-status
            Set warning threshold for status (Default: ''). Can used special
            variables like: %{id}, %{role}, %{state}

    --critical-status
            Set critical threshold for status (Default: '%{state} !~ /ready/
            && %{state} !~ /provisioned/'). Can used special variables like:
            %{id}, %{role}, %{state}

            Role can be: 'master', 'member', 'notMember', 'standby'.

            State can be: 'waiting', 'progressing', 'added', 'ready',
            'sdmMismatch', 'verMismatch', 'featureMismatch',
            'newMasterInit', 'provisioned', 'invalid', 'removed'.

When one member is removed or down, it only prints:
CRITICAL: Stack ring is not redundant

I would like to know if it is possible to display the verbose with the member that is removed.

Thanks in advance.

**Comment by amitsamy** [comment]
Hello Quentin,

Can you help me?

**Comment by da-friedl** [comment]
HI, after the review of Sims24 i closed #1488 and re-commited a new PR with #1503.

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk when you have the issue ?
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.9.9.500.1 > cisco.snmpwalk

**Comment by garnier-quentin** [comment]
It should be ok with the last version

**Comment by Cancom-Monitoring** [comment]
Hi, we experience same issue.
Our guys from network dept. sent me following information regarding **stackwise virtual**:

Cisco-Stack-Master-Status	OID: 	1.3.6.1.4.1.9.9.500.1.2.1.1.6.2		

type	value	description	alerting
Integer	1	Waiting	Warning
Integer	2	Progressing	Warning
Integer	3	Added	Warning
Integer	4	Ready	Good
Integer	5	sdmMismatch	Critical
Integer	6	VerMismatch	Critical
Integer	7	featureMismatch	Critical
Integer	8	newMasterInit	Warning
Integer	9	Provisioned	Critical
Integer	10	Invalid	Critical
Integer	11	Removed	Critical


Cisco-Stack-Master-Role	OID: 	1.3.6.1.4.1.9.9.500.1.2.1.1.3.2		

type	value	description	alerting
Integer	1	Master	Good
Integer	2	Member	Critical
Integer	3	notMember	Warning
Integer	4	Standby	Warning


Cisco-Stack-Member-Status	OID:	 1.3.6.1.4.1.9.9.500.1.2.1.1.6.500	

type	value	description	alerting
Integer	1	Waiting	Warning
Integer	2	Progressing	Warning
Integer	3	Added	Warning
Integer	4	Ready	Good
Integer	5	sdmMismatch	Critical
Integer	6	VerMismatch	Critical
Integer	7	featureMismatch	Critical
Integer	8	newMasterInit	Warning
Integer	9	Provisioned	Critical
Integer	10	Invalid	Critical
Integer	11	Removed	Critical


Cisco-Stack-Member-Role	OID:	1.3.6.1.4.1.9.9.500.1.2.1.1.3.500	

type	value	description	alerting
Integer	1	Master	Warning
Integer	2	Member	Critical
Integer	3	notMember	Warning
Integer	4	Standby	Good

**Comment by garnier-quentin** [comment]
Have you tested with last version ?

**Comment by Cancom-Monitoring** [comment]
Yes, tested with plugins replicated from git yesterday

Von: qgarnier ***@***.***>
Gesendet: Freitag, 19. November 2021 11:51
An: centreon/centreon-plugins ***@***.***>
Cc: EXT SCM Monitoring ***@***.***>; Comment ***@***.***>
Betreff: Re: [centreon/centreon-plugins] Centreon Plugin - Check Cisco Stack (CISCO-STACKWISE-MIB). (#1487)


Have you tested with last version ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://protect-de.mimecast.com/s/RsXnC6WDxOFoz8W8ipfTNr?domain=github.com>, or unsubscribe<https://protect-de.mimecast.com/s/pH40C79EyPImloRoSWBeNo?domain=github.com>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect-de.mimecast.com/s/bB6GC83GzQtj1LkLC2sEwG?domain=apps.apple.com> or Android<https://protect-de.mimecast.com/s/nu_PC99JA0ImQ9O9SOjv6B?domain=play.google.com>.



Peter Körner
Team Leader Monitoring

***@***.***


CANCOM Managed Services GmbH
Erika-Mann-Straße 69
80636 München
Deutschland


Phone    +49 89 54054-5496
Fax      +49 8225 996-45496
Mobile   +49 151 16225279

***@***.******@***.***>
http://www.cancom.de

***@***.***<https://de.linkedin.com/company/cancom> ***@***.*** <https://www.instagram.com/cancom.se/>  ***@***.*** <https://twitter.com/cancom_se>  ***@***.*** <https://www.facebook.com/CANCOM/>  ***@***.*** <https://www.youtube.com/c/cancom>  ***@***.*** <https://www.xing.com/company/cancom>


CANCOM Managed Services GmbH
Sitz der Gesellschaft: München
HRB 249726 München
Geschäftsführer: Rüdiger Rath, Thomas Stark, Petra Trost-Gürtner


Diese E-Mail und alle mit gesendeten Dateien sind vertraulich und ausschließlich für den Gebrauch durch den Empfänger bestimmt!
This e-mail and any files transmitted with it are confidential intended solely for the use of the addressee!

***@***.***
<http://www.cancom.info>



<http://www.cancom.com/Presse/Pressemitteilungen/tabid/158/controlToLoad/ViewNote/noteId/469/language/de-DE/Default.aspx>

**Comment by garnier-quentin** [comment]
Need the snmpwalk: snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.9.9.500.1 > cisco.snmpwalk

**Comment by Cancom-Monitoring** [comment]
Voilà…

Von: qgarnier ***@***.***>
Gesendet: Freitag, 19. November 2021 12:09
An: centreon/centreon-plugins ***@***.***>
Cc: EXT SCM Monitoring ***@***.***>; Comment ***@***.***>
Betreff: Re: [centreon/centreon-plugins] Centreon Plugin - Check Cisco Stack (CISCO-STACKWISE-MIB). (#1487)


Need the snmpwalk: snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.9.9.500.1 > cisco.snmpwalk

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://protect-de.mimecast.com/s/xYtQCk2YjqUn9WW2I24V7U?domain=github.com>, or unsubscribe<https://protect-de.mimecast.com/s/qSBEClRZkrUoxnnRt9quAY?domain=github.com>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect-de.mimecast.com/s/DVkUCmq10vt5zJJyfBJX2p?domain=apps.apple.com> or Android<https://protect-de.mimecast.com/s/yGmrCnR2mwUGvOO9SZ9dib?domain=play.google.com>.



Peter Körner
Team Leader Monitoring

***@***.***


CANCOM Managed Services GmbH
Erika-Mann-Straße 69
80636 München
Deutschland


Phone    +49 89 54054-5496
Fax      +49 8225 996-45496
Mobile   +49 151 16225279

***@***.******@***.***>
http://www.cancom.de

***@***.***<https://de.linkedin.com/company/cancom> ***@***.*** <https://www.instagram.com/cancom.se/>  ***@***.*** <https://twitter.com/cancom_se>  ***@***.*** <https://www.facebook.com/CANCOM/>  ***@***.*** <https://www.youtube.com/c/cancom>  ***@***.*** <https://www.xing.com/company/cancom>


CANCOM Managed Services GmbH
Sitz der Gesellschaft: München
HRB 249726 München
Geschäftsführer: Rüdiger Rath, Thomas Stark, Petra Trost-Gürtner


Diese E-Mail und alle mit gesendeten Dateien sind vertraulich und ausschließlich für den Gebrauch durch den Empfänger bestimmt!
This e-mail and any files transmitted with it are confidential intended solely for the use of the addressee!

***@***.***
<http://www.cancom.info>



<http://www.cancom.com/Presse/Pressemitteilungen/tabid/158/controlToLoad/ViewNote/noteId/469/language/de-DE/Default.aspx>

**Comment by garnier-quentin** [comment]
I don't see the snmpwalk

**Comment by Cancom-Monitoring** [comment]
[cisco.snmpwalk.TXT](https://github.com/centreon/centreon-plugins/files/7570919/cisco.snmpwalk.TXT)

**Comment by garnier-quentin** [comment]
Could you also provide a snmpwalk of the following branch ? 1.3.6.1.2.1.47.1.1.1.1

**Comment by garnier-quentin** [comment]
You can test with last git version. You'll see the second member now

**Comment by Cancom-Monitoring** [comment]
./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --snmp-community=public --snmp-version=2c --mode=stack --snmp-timeout=60 --snmp-retries=0 --verbose --hostname=x.x.x.x
CRITICAL: Stack status is 'notredundant' | 'waiting'=0;;;0; 'progressing'=0;;;0; 'added'=0;;;0; 'ready'=2;;;0; 'sdm_mismatch'=0;;;0; 'version_mismatch'=0;;;0; 'feature_mismatch'=0;;;0; 'new_master_init'=0;;;0; 'provisioned'=0;;;0; 'invalid'=0;;;0; 'removed'=0;;;0;
Member 'Switch 1 Chassis' state is 'ready', role is 'master'
Member 'Switch 2 Chassis' state is 'ready', role is 'standby'

**Comment by garnier-quentin** [comment]
You have the same issue: https://github.com/centreon/centreon-plugins/issues/2818
notredundant comes from cisco equipment. i dont know why. you should ask to your support
