### ISSUE TITLE
Linux memory usage calculation bug

### ISSUE THREAD

**Issue by Tagazoc** [centreon/centreon-plugins#1653]
Hi there,
I use CentOS 7.7 with regular updates, and a recent net-snmp update broke memory usage calculation from centreon ("used" metric was often negative).

I currently use (old) RPM centreon-plugins-2.8.26-3.el7.centos.noarch, but I quickly tried the last CentOS version and problem still showed up.

It seems that the calculation of the "-buffers/cache" usage is already done by net-snmp.
I managed to fix the problem in file centreon_linux_snmp.pl, line 8841 : 

      my $nobuf_used = $physical_used ;  # - $buffer_used - $cached_used;

However I don't know how you can discover that calculation has already been done ; it is easy if the result is negative, but if it is not...?

Good luck and thanks for your work

Tagazoc

**Comment by garnier-quentin** [comment]
Sometimes it's not negative. You can use the last version. You have 2 options: --redhat or --autodetect-redhat.

**Comment by Tagazoc** [comment]
Thanks for the quick response. Unfortunately this last version seems not to be yet in the CentOS repositories.

**Comment by garnier-quentin** [comment]
It's in unstable repository.

**Comment by florianncy** [comment]
Hello,

I have the same problem : https://github.com/centreon/centreon/issues/7867

**Comment by cgagnaire** [comment]
Hi,
Calculation methods for both procps and snmp have changed since version 7.7.
We first though that it was only affecting RedHat distribution but finally CentOS will also be impacted.
So we did create a --redhat option to deal with it, and --autodetect-redhat to be smarter.
You can use it from the project, or from the packaged fatpacks from the Centreon unstable repository.
Calculation is explained here : 
https://github.com/centreon/centreon-plugins/blob/a77e1e0bd10aa53a83aaf96021ff5d905d67d203/snmp_standard/mode/memory.pm#L238
