### ISSUE TITLE
[network::cisco::standard::snmp::plugin] packets_discard %

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1731]
Hello

It seems to me that the percent values in the perfdata are calculated somehow wrong (2251.71%)

```
# ./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin 
--mode=interfaces 
--add-traffic --warning-in-traffic=98 --warning-out-traffic=98 --units-traffic='%' 
--add-errors --warning-in-crc=1 --warning-in-error=1 --warning-in-discard=1 
--warning-out-error=1 --warning-out-discard=1 --add-err-disable 
--critical-status='%{errdisable} ne "-"'  
--filter-uom='%' 
--snmp-community='public' --hostname='10.3.2.35' --snmp-version=2

WARNING: Interface 'Gi1/0/11' Packets Out Discard : 2251.71% (1313357) | 

...
'traffic_in_Gi1/0/11'=949945.74;0:980000000;;0;1000000000 
'traffic_out_Gi1/0/11'=27434397.22;0:980000000;;0;1000000000 
'packets_discard_in_Gi1/0/11'=0.00%;0:1;;0;100 
'packets_error_in_Gi1/0/11'=0.00%;0:1;;0;100 
'packets_discard_out_Gi1/0/11'=2251.71%;0:1;;0;100 
'packets_error_out_Gi1/0/11'=0.00%;0:1;;0;100 
'packets_crc_in_Gi1/0/11'=0.00%;0:1;;0;100 
...
```
![Cisco](https://user-images.githubusercontent.com/17614847/69028667-ba892e00-09e3-11ea-8e28-310ed4c42c52.png)

**Comment by garnier-quentin** [comment]
Seems high yes :) Need two snmpwalk (5min between them for example). You always get that high value ?

**Comment by Aleksey-Maksimov** [comment]
What root OID to use for snmpwalk? 
The values are different - sometimes small 1-5%, and sometimes very large up to several thousand%

**Comment by garnier-quentin** [comment]
.1.3.6.1.2.1

**Comment by Aleksey-Maksimov** [comment]
[Cisco_probe1.zip](https://github.com/centreon/centreon-plugins/files/3857765/Cisco_probe1.zip)
[Cisco_probe2.zip](https://github.com/centreon/centreon-plugins/files/3857766/Cisco_probe2.zip)

**Comment by garnier-quentin** [comment]
I don't have the issue with that 2 snmpwalk. Maybe it can comes from interface index change (a router reboot).

**Comment by Aleksey-Maksimov** [comment]
Not. There was no reboot of devices. The problem was found on network core switches at a branch of the company. These switches are always on. I also noticed one strange thing. On the same day, we found a huge percentage of packets_discard_out on several more Cisco Catalyst switches only in this branch. But after that the problem is not reproduced.

**Comment by garnier-quentin** [comment]
it will be difficult to fix it without snmpwalk before and after.

**Comment by Aleksey-Maksimov** [comment]
Good. I will monitor the situation. If the problem persists again, then I will open this thread. In the meantime, we assume that the issue is closed. Thanks.

**Comment by trentasis** [comment]
Hi @Aleksey-Maksimov 

Have you solved this issue with bad percentatge on discards? 
I have tried with latest versions centreon-plugins and same error, can you give detail how do you solved?

thanks

**Comment by UrBnW** [comment]
Strangely enough, I'm facing same sort of bug with Juniper EX.
To sum-up, the `ifOutDiscards` SNMP counter may not correctly be accounted / reported by the device itself, leading to number of out-discarded packets greater than 100% !

According to the IF-MIB RFC :
https://tools.ietf.org/html/rfc3635
"_ifOutDiscards and ifOutErrors are counted by ifOutXcastPkts_".

Also confirmed in this other related RFC :
https://tools.ietf.org/html/rfc2863
"_ifOutXcastPkts : The total number of packets that higher-level protocols requested be transmitted, including those that were discarded or not sent_".

Let's then request `ifOutXcastPkts` OIDs (unicast, multicast, broadcast), both 64 and 32 bit versions, and `ifOutDiscards` OID.
Below are 2 queries made at 5 minutes interval :
```
# total out packets (64bit counters):     798638956
.1.3.6.1.2.1.31.1.1.1.11.830 = Counter64: 627261379
.1.3.6.1.2.1.31.1.1.1.12.830 = Counter64:  71685524
.1.3.6.1.2.1.31.1.1.1.13.830 = Counter64:  99692053
# total out packets (32bit counters):     798638956
.1.3.6.1.2.1.2.2.1.17.830 = Counter32:    627261379
.1.3.6.1.2.1.31.1.1.1.4.830 = Counter32:   71685524
.1.3.6.1.2.1.31.1.1.1.5.830 = Counter32:   99692053
# total discard out :
.1.3.6.1.2.1.2.2.1.19.830 = Counter32:    481566809

# total out packets (64bit counters) :    798656216
.1.3.6.1.2.1.31.1.1.1.11.830 = Counter64: 627274295
.1.3.6.1.2.1.31.1.1.1.12.830 = Counter64:  71687472
.1.3.6.1.2.1.31.1.1.1.13.830 = Counter64:  99694449
# total out packets (32bit counters) :    798656216
.1.3.6.1.2.1.2.2.1.17.830 = Counter32:    627274295
.1.3.6.1.2.1.31.1.1.1.4.830 = Counter32:   71687472
.1.3.6.1.2.1.31.1.1.1.5.830 = Counter32:   99694449
# total discard out :
.1.3.6.1.2.1.2.2.1.19.830 = Counter32:    481618265
```
Which lead to the following percentage of out-discarded packets across this period :
`(481618265 - 481566809) x 100 / (798656216 - 798638956) = 298% !`

A situation which should not occur, as, according the the RFCs, discarded packets should increase both `ifOutDiscards` and `ifOutXcastPkts` counters.

I then tend to say that the issue is at the device level.
I should manage to open a Juniper case in the coming days.
Would be interesting to have Cisco feedback on this too, with same sort of report.

**Comment by trentasis** [comment]
With DEll OS10 also fails, and I think that is a Debian distribution.

Do you have any workaround, I have tried to configure absolute but % is also showed with a incorrect %, any suggestion?

thanks

**Comment by UrBnW** [comment]
IMO there's no proper workaround no, as these devices do not seem to correctly compute these counters (or I miss something)...
And there's no way to guess whether or not they compute them correctly before effectively seing `ifOutDiscards` >100%...
Suggestion would be to contact device' support / dev team, to have their feedback, so that a proper fix could be found.

**Comment by trentasis** [comment]
I'm not really sure, because if you configure with absolute mode and no %, I understand taht no % is needed, but is showed, Is this correct?

I like to configure with absolute values, do you know how to do this without sowing any % errors?

thanks
