### ISSUE TITLE
[storage::synology::snmp::plugin] Warning option unknown

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#217]
Hi team,
I use this command for my synology, and for the mode "components" doesn't use "Warning" &"Critical", so i got an error message:
Unknown option: warning

$USER1$/centreon-plugins/centreon_plugins.pl --plugin=$_SERVICEPLUGIN$ --mode=$_SERVICEMODE$ --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$ $_SERVICEOPTION$ $_SERVICEOPTION$ --host=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$

Do I have to create a special command for that?without warning and critical?

Thanks

**Comment by garnier-quentin** [comment]
I'm sorry but you need to use option for good modes Matthieu.

**Comment by matthieu-robin** [comment]
It worked 1 month ago :-(

**Comment by garnier-quentin** [comment]
Yes. I know.

**Comment by matthieu-robin** [comment]
very sad... more command lines...  :-1:

**Comment by julienmathis** [comment]
Yes but we had problem with our plugins packs. Some packs have used templates who accidentaly have a bad name options for thresholds. Because centreon-plugins didn't notify that the option is not existing, users missed some alarms. We prefer changing the behavior it in order to avoid this kind of problem.

**Comment by matthieu-robin** [comment]
No problem, I can understand! I'll modify my templates :-)
