### ISSUE TITLE
[network::paloalto::snmp::plugin] gp-usage metrics issues

### ISSUE THREAD

**Issue by lune001** [centreon/centreon-plugins#2175]
The GlobalProtect for PaloAlto SNMP plugin is working great but their is too many metrics return : globalprotect tunnels count but also trafic for all interface !
Could you correct this issues ?
Regards
![GlobalProtectIssue](https://user-images.githubusercontent.com/3175414/91421907-c9481f80-e856-11ea-8715-6b732dfa36c0.png)

**Comment by thibaults-centreon** [comment]
The only metrics set by the gp-usage mode are the globalprotect ones. 
You probably have these traffic metrics here because you configured this gp-usage service over an existing traffic/interfaces service, so the old metrics remain in the database. You can clean up these metrics in the menu Administration > Parameters > Data

**Comment by lune001** [comment]
Ok thanks thibaults-centreon it's working now
