### ISSUE TITLE
hardware::server::dell::idrac::snmp::plugin - Ready disk appears as Warning

### ISSUE THREAD

**Issue by TomSVT** [centreon/centreon-plugins#2442]
Hello,

I think that since #2165 , `ready` disks, wich state is expected, appears as warning in Centreon.

![image](https://user-images.githubusercontent.com/76195801/102576544-13029180-40f6-11eb-8dbe-a57a7694a7c4.png)

On my setup this disk is just a single pdisk wich is not part of a raid. Actually they are NVME disk mirrored by our Datacore SAN.

Could you introduce a switch to ignore the warning state ?

Thank you

**Comment by garnier-quentin** [comment]
You can use following option: ```--threshold-overload='pdisk.state,OK,ready'

**Comment by TomSVT** [comment]
Hello Quentin,

I thank you for your answer and your tip.
Altought, I do think that my setup is the most common and that the overload should be used by people with raid only configuration.

Tom

**Comment by garnier-quentin** [comment]
Maybe yes.

**Comment by garnier-quentin** [comment]
but why others disks are ok and not ready ?

**Comment by TomSVT** [comment]
Hello Quentin,

Look at this other server. Their is a RAID 1 with two disks (0 and 1) and the disk 2 is a single disk wich is not part of any raid.
![image](https://user-images.githubusercontent.com/76195801/102683027-36007480-41ce-11eb-8c37-002cf41aedbf.png)

I think that the state `ready` means that the disk is ready to be include in a raid. 
The status is `ok` for every disk.

**Comment by UrBnW** [comment]
`ready` more or less means that the disk is ready to be configured.
But it will not be automatically used as a spare device until you configure it for this purpose, which is then a risky situation.
This is why #2165 now checks whether or not `ready` devices have properly been declared as spare devices, introducing 2 new states, `readySpareDedicated` and `readySpareGlobal`.

`ready` state has then been set to `WARNING`, so that admin gets alerted that there's something that may not be expected within its configuration.
`readySpareDedicated` and `readySpareGlobal` states of course are `OK`.

Your above screenshot must be before #2165, and will then remain `OK` with #2165 if spare disks are properly declared as spare, and thus ready to be used by the system if needed, without human intervention 👍

**Comment by UrBnW** [comment]
You should then use `--threshold-overload` option for your first post specific configuration.
You should even stick this option to the concerned disk instances only, so that the "real" spare disks are properly checked.

**Comment by TomSVT** [comment]
Hello Guys

@UrBnW, I thank you for the clarification. 
I did what you and @garnier-quentin  said to filter my ok ready disks.

I do think that with HyperConverged systems like S2D and NVME disks their will be less and less raid only configuration.

Have a great new year's eve !
