### ISSUE TITLE
cloud::azure::web::appserviceplan::plugin BadRequests

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2813]
Hello,

I use this command :

/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::web::appserviceplan::plugin --custommode='api' --mode='tcp-connections' --tenant='xxxx' --client-id='xxxxx' --client-secret='xxxxx' --resource='/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.Web/serverFarms/xxxxx' --timeout 60 --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True" --subscription 'xxxx' --zeroed

I have this error :

UNKNOWN: Management endpoint API returns code 'BadRequest' (add --debug option for detailed message)

I can send the debug in email ;)

Thank you

**Comment by thibaults-centreon** [comment]
hello, please send the debug to my email
Thanks

**Comment by prohand** [comment]
Hello,

I send the email ;)

Thank you

**Comment by thibaults-centreon** [comment]
Thanks for the mail.
The issue seems to come from the API itself, not from the Plugin.
This message:
``Message : Failed to find metric configuration for provider: Microsoft.Web, resource Type: serverFarms, metric: tcpsynsent , Valid metrics: CpuPercentage,MemoryPercentage,DiskQueueLength,HttpQueueLength,BytesReceived,BytesSent,TcpSynSent,TcpSynReceived,TcpEstablished,TcpFinWait1,TcpFinWait2,TcpClosing,TcpCloseWait,TcpLastAck,TcpTimeWait,SocketInboundAll,SocketOutboundAll,SocketOutboundEstablished,SocketOutboundTimeWait,SocketLoopback```
indicates that the requested metric cannot be found although it's indicated in the list...

Can you try to comment lines 80 to 95 in /cloud/azure/web/appserviceplan/mode/tcpconnections.pm and test again?

**Comment by prohand** [comment]
Yes it's ok after comment the lines 80 to 95

Thank you

**Comment by thibaults-centreon** [comment]
OK thanks for the feedback, I'll remove these metrics for now
