### ISSUE TITLE
Add Missing Information for StoreOnce plugin

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#2925]
Hi,

Could you add this url for StoreOnce Plugin. Some information are missing in the plugin. ( State of Drive for exemple )

![image](https://user-images.githubusercontent.com/12545407/124137947-79457500-da86-11eb-9183-a288e982efd1.png)

https://IP/api/v1/data-services/dashboard/appliance/localhost

[StoreOnce.zip](https://github.com/centreon/centreon-plugins/files/6748722/StoreOnce.zip)

**Comment by garnier-quentin** [comment]
It's the new API: https://github.com/centreon/centreon-plugins/issues/2575
I didn't manage the new API (yet).

**Comment by romsworld** [comment]
Hum, ok, thanks :)

**Comment by christophe-activiumid** [comment]
Hello
I'm here to second the need of hardware status from the API

the HPe iLO hardware check only return local chassis disks, but with additional external chassis this is not managed by the iLO card
we almost lost data because no one had checked in detail that specific hardware manually in a while.

if there is a need of a working storeonce to debug/dev let me know

**Comment by garnier-quentin** [comment]
@christophe-activiumid we can do a session. I will check and get information to manage the new API. You can send me an email and we'll schedule the meeting.

**Comment by garnier-quentin** [comment]
You can test the new plugin: https://github.com/centreon/centreon-plugins/pull/3682
