### ISSUE TITLE
[hardware::devices::video::axis::snmp::plugin] Missing information

### ISSUE THREAD

**Issue by stevegoffaux** [centreon/centreon-plugins#3531]
Hi, 

I have Axis cameras that I want to monitor with centreon.
I use the following command: 
./centreon_plugins.pl --plugin=hardware::devices::video::axis::snmp::plugin --mode=environment --snmp-version=2c --snmp-community= 'XXXX' --hostname='XXX' --component="temperature"

and the response is: 
OK: All 0 components are ok []. |
Checking temperatures

Shouldn't it display temperature?

Thans for your answers

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following branch: .1.3.6.1.4.1.368 ? And also MIB files of your equipment.

**Comment by stevegoffaux** [comment]
Hi, 
As it's old material I found this:
https://mibs.observium.org/mib/AXIS-VIDEO-MIB/

and for other request
snmpwalk -v 2c -c 'XXX' xx.xx.xx.xx -O n .1.3.6.1.4.1.368
.1.3.6.1.4.1.368 = No Such Object available on this agent at this OID

Thanks

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @stevegoffaux if you still need a response / solution to this issue, as Quentin asked you, can you provide us an anonymized .snmpwalk of your equipment to help us troubleshooting this issue ?
Otherwise we will be forced to close this issue.

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time.Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the issue.
