### ISSUE TITLE
Centreon's Meraki plugin can abuse the Meraki dashboard API

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [centreon/centreon-plugins#3917]
Hi folks! We're thrilled to see your consumption of the Meraki dashboard API. Unfortunately, [this module](https://github.com/centreon/centreon-plugins/blob/eebd4756bc4c4a27b4e21e3025e71981ffb98285/network/cisco/meraki/cloudcontroller/restapi/custom/api.pm) doesn't obey the Meraki retry-after header, and therefore can result in abuse of the Meraki API. 

The offending line of code seems to be this minimalist logic for handling 429s. It doesn't take into account the retry-after header when waiting to make the next response, which violates Meraki API best practices.

```
        if ($code == 429) {
            sleep(1);
            next;
        }
```

This requirement [is documented in Meraki's API docs site](https://developer.cisco.com/meraki/api-v1/#!rate-limit) and we would really like to see the Centreon plugins updated to follow this best practice to avoid interruptions to Centreon's usage of the Meraki dashboard API. 

If there are any other areas of the Centreon product which call the Meraki API, please ensure that they also obey this best practice when invoking the Meraki API.

Thanks in advance, and feel free to reach out to me if you have any questions. 

Kindly,
John Kuchta

**Comment by Sims24** [comment]
Hi @TKIPisalegacycipher 

Thanks for taking the time to post your feedback here. We will manage the retry-after as requested to stick with Cisco best practices.

Nevertheless, it will probably be pointless against a huge Meraki deployment and will likely degrade the monitoring performance and experience. 

We are more than aware that Meraki cannot handle a reasonable of requests when there is multiple organizations, network and devices and that's why we added some options that can be leveraged to do the minimum number of queries against the API: 

`--plugin=network::cisco::meraki::cloudcontroller::restapi::plugin --mode=cache` 

The mode above is responsible for the cache generation and refresh, and all others plugins execution uses this same cache thanks to options below: 

`--mode=<yourmode> --cache-use --skip-clients  --skip-performance --skip-connections` 

Hope this help
Cheers,
Simon

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3919
