### ISSUE TITLE
[os::windows::snmp::plugin] --mode=storage - threshold Free space in B

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#426]
Hello,

I want to make an alert concerning the free space on my disk in B.

For example:
Warning: When the free space is under than 10GB
Critical: When, the free space is under than 5GB

But I don't know how make it... :\
Can you help me?

Thanks

**Comment by Sims24** [comment]
Hello Benoit, 

Here is a sample : 

 su - centreon-engine -c "/usr/lib/nagios/plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --mode storage --storage / --hostname 127.0.0.1 --name --free --units 'B' --critical 127610881:"

CRITICAL: Storage '/' Total: 975.90 MB Used: 854.20 MB (87.53%) Free: 121.70 MB (12.47%) | 'free'=127606784B;;127610881:;0;1023303680

Important options are --free --units 'B' --critical 127610881: 

: is important and also be carefull of your perfdata that will become free instead of used.

Regards

**Comment by benoitb21** [comment]
Ok thanks,

Think you it's possible to improve this plugin in order to choose if the perfdata is 'used' or 'free'? And more if it's possible to use a full unit (MB, GB etc...) in the thresholds to replace the argument '--units'.
To resume, as the same usage that the old Centreon plugin. In the old script, if you used a 'B' unit, it was automatically a free space, and by default a percent.

Thanks

**Comment by garnier-quentin** [comment]
Duplicated ticket #79
