### ISSUE TITLE
haproxy : check via stats instead of snmp

### ISSUE THREAD

**Issue by Rico29** [centreon/centreon-plugins#4271]
Hello

Haproxy community edition does not embed any snmp support. It would be interesting to have a module which get metrics from stats socket instead of snmp.

Example haproxy config : 

```
listen stats
    bind :9000 # Listen on :9000
    mode http
    stats enable  # Enable stats page
    #stats hide-version  # Hide HAProxy version
    stats realm Haproxy\ Statistics  # Title text for popup window
    stats uri /haproxy_stats  # Stats URI
    http-request use-service prometheus-exporter if { path /metrics }
    #stats auth login:password  # Authentication credentials
```

Metrics are available using for example : 

```
# curl 'http://127.0.0.1:9000/haproxy_stats;<format>'
with format = csv or json
```
result example attached
[haproxy_stats.json.txt](https://github.com/centreon/centreon-plugins/files/10929244/haproxy_stats.json.txt)

Regards
Cédric

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request is old so let me close it because enhancement request are done [here](https://thewatch.centreon.com/ideas) to be take into account and vote on. In this case, the enhancement ticket already exist in our backlog, you may have news in future about it.
Thank you for your understanding.
