### ISSUE TITLE
[hardware::ups::hp::snmp::plugin] Missing alert for failed battery test and battery status "aging"

### ISSUE THREAD

**Issue by Cynexxde** [centreon/centreon-plugins#4519]
Hello together, with the Plugin (hardware::ups::hp::snmp::plugin) I don't get a message when the battery test fails or the battery goes into the "Aging" status. 

The battery test fail if a problem with the battery is detected.

The "aging" status is reached when the HPE recommended replacement date is exceeded. The date is displayed on the Webinterface of the UPS.

If you have any questions, please do not hesitate to contact me.

![image](https://github.com/centreon/centreon-plugins/assets/88704661/4b014b60-e5c0-4342-9d36-50d9598e0307)
![image](https://github.com/centreon/centreon-plugins/assets/88704661/4d36642f-9945-417d-87ba-1da45d95358e)

**Comment by garnier-quentin** [comment]
I need the snmpwalk and mib files.

**Comment by Cynexxde** [comment]
[cpqpower1.80.zip](https://github.com/centreon/centreon-plugins/files/11903809/cpqpower1.80.zip)
[UPS-MIB.zip](https://github.com/centreon/centreon-plugins/files/11903810/UPS-MIB.zip)

**Comment by Cynexxde** [comment]
So it looks like the battery replacement date is not output. That is not so problematic now.

However, the status of the last battery test is returned via the following OID.  Could you implement it so that there is a message if it not says "Battery test OK"?

.1.3.6.1.4.1.232.165.1.1.2.0 = STRING: "Battery test failed"
.1.3.6.1.4.1.232.165.1.1.2.0 = STRING: "Battery test OK"

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is now an enhancement request rather than a bug report, so let me close it. If you still need this enhancement we will need an .snmpwalk to test it, there is the command for a full snmpwalk of enterprise branch : 
`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`
Also for now enhancement requests are addressed [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
