### ISSUE TITLE
[apps::monitoring::speedtest::plugin] Cannot decode response

### ISSUE THREAD

**Issue by liferadioat** [centreon/centreon-plugins#4799]
Hi,

the command `sudo -u nagios perl centreon_plugins.pl --plugin=apps::monitoring::speedtest::plugin --mode=internet-bandwidth` results in UNKNOWN: Cannot decode response

What could be the reason?

**Comment by sistemmsn** [comment]
#4729 You need to install the module as it is, I will explain how to correct it.

**Comment by lucie-dubrunfaut** [comment]
Hello @liferadioat , 

I have read the discussions you had on Issue [#4729](https://github.com/centreon/centreon-plugins/issues/4729) and I would like to refocus the problem here (the issue in question is already closed).

There were two proposed solutions. That of updating the [speedtest version](https://github.com/centreon/centreon-plugins/issues/4729#issuecomment-1800424973) and that of checking the user who has the necessary [license](https://github.com/centreon/centreon-plugins/issues/4729#issuecomment-1884550145) to be able to make the request.

From your last message I don't really understand where your problem lies now. And I'm not sure I understand what `icingaweb2` is referring to in your question.

**Comment by liferadioat** [comment]
Hi @lucie-dubrunfaut,
unfortunatelly it doesn´t work for me. I followed the other github issue and run the command with the nagios user which is performing the task, also root, but it seems that the license aggreement (first manual run) helps me for using it at icinga2 itself via centreon speedtest.

**Comment by lucie-dubrunfaut** [comment]
So it doesn't work directly but an indirect solution still allows you to obtain the expected final behavior?

**Comment by liferadioat** [comment]
No, it doesn´t work for me at all, because running it manually at command line doesn´t send the value to my icinga2 monitoring system. Perhaps there is a new command parameter needed like "--agree-tos", which could solve it.

**Comment by lucie-dubrunfaut** [comment]
Oh ok, I understand the problem better I think. It's not that the plugin fails to display the result (since on the command line it seems to work according to this [message](https://github.com/centreon/centreon-plugins/issues/4729#issuecomment-1886733665)), it's that via icinga2 monitoring system the plugin returns an error. Can you tell me witch one exactly ?

`UNKNOWN: Cannot decode response`
Or
`UNKNOWN: Command error: ============================================================= ==================================`

Can you tell me more about this `"--agree-tos"` command parameter idea ?

**Comment by liferadioat** [comment]
Till now I get:

`UNKNOWN: Cannot decode response`

It seems related to the problem mentioned that the non commercial license agreement is missing. So I think the parameter --agree-tos could solve the issue to ensure that the command itself is executed and not stopped by the interactive dialogue.

**Comment by lucie-dubrunfaut** [comment]
I think I'm starting to understand the problem, I'll look into discussing the possibility of this option and I'll come back to you when I know more about it.

**Comment by lucie-dubrunfaut** [comment]
Hello @liferadioat,

We have discussed internally the possibility of considering an `--agree-tos` option however we believe it is important that the user reads this information to accept it. In the case of your problem, the solution proposed by Tanguy [here](https://github.com/centreon/centreon-plugins/issues/4729#issuecomment-1884550145) explains how when installing speedtest you can validate this license (it is important that it is validated by the user who is doing the supervision, in the case of centreon user centengine). You must follow a similar procedure for your monitoring system or request support from them.
I am closing this issue for which is not a problem with the plugin involved itself and a solution within the framework of centreon supervision exists.
