### ISSUE TITLE
[apps::protocols::http::plugin] Unknown output with curl backend

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#4877]
Hi,

With 500 http error code, i have :
UNKNOWN: 450 Timeout reached

I have same result with --opt-exit=critical and/or --change-exit=unknown=critical  ( UNKNOWN: 450 Timeout reached )

I expect to get a critical on a 5xx error.

Best regards,

**Comment by gagzou** [comment]
Hi, do you have any news for this fix ?
Thanks

**Comment by lucie-dubrunfaut** [comment]
Hello,

I created a ticket to analyze this bug, you will be kept informed when this subject will move forward, thank you for your feedback.

**Comment by garnier-quentin** [comment]
Could you provide the complete command line and the result with --debug option ?

**Comment by gagzou** [comment]
Hi,

The error only occurs if the time is greater than 5s.

/usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=127.0.0.1 --proto='https' --port='443' --hostname='*********' --urlpath='/' --method='GET' --warning='2' --critical='3' --warning-status='' --critical-status='%{http_code} < 200 or %{http_code} >= 300'  --http-backend=curl --extra-stats --opt-exit=critical
CRITICAL: 500 Internal Server Error, response time 4.244s | 'time'=4.244s;0:2;0:3;0; 'size'=0B;;;0; 'resolve'=13.214ms;;;0; 'connect'=13.214ms;;;0; 'tls'=23.119ms;;;0; 'processing'=4185.900ms;;;0; 'transfer'=13.214ms;;;0;

/usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=127.0.0.1 --proto='https' --port='443' --hostname='*********' --urlpath='/' --method='GET' --warning='2' --critical='3' --warning-status='' --critical-status='%{http_code} < 200 or %{http_code} >= 300'  --http-backend=curl --extra-stats --opt-exit=critical
CRITICAL: 450 Timeout reached, response time 5.012s | 'time'=5.012s;0:2;0:3;0; 'size'=0B;;;0; 'resolve'=0.911ms;;;0; 'connect'=0.911ms;;;0; 'tls'=12.426ms;;;0; 'processing'=-14.104ms;;;0; 'transfer'=0.911ms;;;0;

**Comment by gagzou** [comment]
Which corresponds to this portion of code in the connector:

```
 if ($self->{response_code} == 500) {
          my $client_warning = $self->get_header(name => 'Client-Warning');
          if (defined($client_warning) && $client_warning eq 'Internal response' && $self->{response_message} =~ /connection timed out/mi) {
              $self->{response_code} = 450;
              $self->{response_message} = 'Timeout reached';
          }
      }
```

**Comment by omercier** [comment]
Hi @gagzou,
In your last command results, you seem to have successfully obtained a CRITICAL status following your 450 HTTP response. Is it solved for you?
If not, as @garnier-quentin said, it would help us understand what is the issue if we had the output provided by the `--debug` option.

**Comment by omercier** [comment]
Hi,
I think this issue relates to [this older one](https://github.com/centreon/centreon-plugins/issues/3362).

**Comment by omercier** [comment]
For people who may face the same disagreement, I'll summarize my understanding and what workaround has been identified together.

The issue was reproduced by setting up a mocked http server (at Centreon we use Mockoon) to deliver a 500 error after 6 seconds.

You need to know that libcurl artificially sets the error code to 500 in case of a timeout. This can be annoying if you want to track the real 500 errors and not be distracted with timeouts. So after the discussion here #3362 our HTTP plugins started replacing the artificial 500 code with another artificial code, 450 (supposed to mean `Blocked by Windows Parental Controls`, not very likely in our context) in order to differentiate those two situations : timeout vs 500 error.

In @gagzou's case, if I remember correctly, the server took a long time to deliver 500 errors, sometimes longer than the plugin's timeout, so:
- the plugin returned an UNKNOWN state with 450 error
- the HTTP server's log actually had 500 errors that were not detected by the monitoring tool (although provoked by it)

The adequate solution for this specific use case was to set a longer timeout for the plugin (longer than the likely maximum server response time) and a critical warning for time shorter than it.

Here's the result that seemed right:

```
$ perl centreon_plugins.pl  --plugin=apps::protocols::http::plugin --mode=response --hostname=127.0.0.1 --proto='http' --port='3000'  --urlpath='/' --method='GET' --warning-status='' --critical-status='%{http_code} < 200 or %{http_code} >= 300' --http-backend=curl --extra-stats --opt-exit=critical --debug --critical-time=5 --timeout=10
CRITICAL: 500 Internal Server Error, response time 6.021s | 'time'=6.021s;;0:5;0; 'size'=2B;;;0; 'resolve'=0.044ms;;;0; 'connect'=0.044ms;;;0; 'processing'=6008.109ms;;;0; 'transfer'=0.044ms;;;0;
== Info:   Trying 127.0.0.1:3000...
== Info: Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
=> Send header: GET / HTTP/1.1
Host: 127.0.0.1:3000
Accept: */*

== Info: Mark bundle as not supporting multiuse
=> Recv header: HTTP/1.1 500 Internal Server Error
=> Recv header: Content-Type: application/json; charset=utf-8
=> Recv header: Access-Control-Allow-Origin: *
=> Recv header: Access-Control-Allow-Methods: GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
=> Recv header: Access-Control-Allow-Headers: Content-Type, Origin, Accept, Authorization, Content-Length, X-Requested-With
=> Recv header: Content-Length: 2
=> Recv header: Date: Tue, 06 Aug 2024 08:12:08 GMT
=> Recv header: Connection: keep-alive
=> Recv header: Keep-Alive: timeout=5
=> Recv header: 
=> Recv data: {}
== Info: Connection #0 to host 127.0.0.1 left intact
```
