### ISSUE TITLE
Sophos EmailServer gateway plugin

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#537]
Hi,

I would loke to write a plugin for Sophos ES gateway, here are some intersting value. I think it's better to display it as counter or email/seconds.

Anyone can help me for that?

[sophos_email_gateway.txt](https://github.com/centreon/centreon-plugins/files/601561/sophos_email_gateway.txt)

I will post the MIB tuesday,

Thanks in advance,

**Comment by Sims24** [comment]
Hi @rk4an 

Thanks for your contributions and informations provided. 

Very firts thing to do is to read the developper guide to understand where to put your plugin and modes, how to use built-in methods and so on ..  https://github.com/centreon/centreon-plugins/blob/master/docs/en/developer/guide.rst . 

Also there is an important part about "coding style guidelines", following theses help us to review the code, maintain it  ... The model class usage is also an important part, because as the code may appear a little bit more complex (more abstraction), it will really make your life easier in option, perfdata, filters management when you write a new plugin !

Feel free to ask any questions during your devs, as I am prelly busy, I'll try to answer as fast as possible.

Simon

**Comment by rk4an** [comment]
Here the Sophos Email Appliance MIB, a lot of useful information for the future plugin 

[ES1000.txt](https://github.com/centreon/centreon-plugins/files/605816/ES1000.txt)

**Comment by garnier-quentin** [comment]
I have done a new plugin for it. Could you test it ?
