### ISSUE TITLE
Question about 'display-transform-src'

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-plugins#629]
Hello

I try to get the usage of disks in a server linux (debian) : 
``centreon_plugins.pl=os::linux::snmp::plugin --host=blabla --mode=disk-usage``

I get : 
used_/, used_/var, ...

done.

now if I try to remove 'used_' in the result with ``--display-transform-src`` and ``--display-transform-dst``, I get the error : ``Unknow option : display-transform-src at Getopt.pm line 67``

my filter is --display-transform-src='^(a-z_)/*'

**Comment by Sims24** [comment]
Hello @sulian 

You should use the --change-perfdata instead of mentionned options that are used for other purpose.

Normally, it would be --change-perfdata 'used_,' ... BUT that do not work because we make a check of option integrity and we don't allow to set substitute part as an undefined value. So example I gave will throw you out. 

On an other hand, maybe I can study code and propose a patch to allow what you want because that could be prelly useful in some situations. 

To give you a better idea of how this work you can in the meantime do --change-perfdata "used_, " but the extra space at the beginning of the line is 'dirty'.

Just to be sure to not miss anything, your need is to remove prefix label of perfdata before disk nothing more ?

**Comment by sulian** [comment]
@Sims24 yes, I want to remove 'used_'

**Comment by Sims24** [comment]
@sulian ok I find a way by setting line 128 of plugins/output.pm like this : 

if (! /^(.+?),(.*)$/) { 

That allow you to define the option like this : 
--change-perfdata 'used_

I'm going to check that this is not breaking anything but looks promising. I'll probably post a PR to @garnier-quentin the git master to validate. 

Thanks

**Comment by Sims24** [comment]
my bad --change-perfdata 'used_(.*),$1' do the tricks without any modification in the core ... 

thanks @garnier-quentin
