### ISSUE TITLE
[enhancement] http::mode::soap/jsoncontent.pm thresholds and output values

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#636]
Hi, 

For jsoncontent.pm and soapcontent.pm, we need to be more flexible on the way we allow to manage thresholds and also on the output.

E.g, if I perform a lookup for healthy node, appearing 40 times in my web service response, I should be able to check how many time it's true or false and display this count instead of the total count. Also I should be able to set my threshold on this counters insteand of only global. 

Also, perfdata management on threshold looks strange to me.

I worked on it and make a PR soon to propose my change. The solution willl ultimately be determined with @garnier-quentin by the end of April. You can in the mean time follow this on my fork.

**Comment by sebastien-prudhomme** [comment]
+1 should be nice to have something like "count_string_ok", "count_string_warning" and "count_string_critical" in output and performance data

**Comment by jdelah** [comment]
Hi,

I'm using the http plugin with the json-content mode. 
It would be great to define the threshold-value with a JSON-XPath string. Because if there is many  values, getting info/perfdata and treshold_value is a bit tricky. 

Explaination : 
Here is a simple JSON
`{
    "errors": 1,
    "Log": "Lorem ipsum..",
    "number": 845
}`

The command i use: 
`./centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=json-content --lookup='$..errors' --hostname='192.168.0.1' --urlpath='/json' --format-ok='No Error' --format-warning='Erreurs : %{values}' --format-critical='Errors : :%{values}' --threshold-value='values' --warning-numeric='10' --critical-numeric='20'`

The command i would like to use : 

`./centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=json-content --lookup='$..*' --hostname='192.168.0.1' --urlpath='/json' --format-ok='No Error' --format-warning='Errors : $..errors, $..log' --format-critical='Errors : $..errors, $..log' --threshold-value='$..errors' --warning-numeric='10' --critical-numeric='20'`

Thank you for reading me ! And thank you for your plugins !!

**Comment by garnier-quentin** [comment]
A new mode collection is out:
https://github.com/centreon/centreon-plugins/pull/3406
