### ISSUE TITLE
database::*::plugin

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#775]
Hello,
I would like to know if the database plugins have particular prerequisites to work well?
Notably because I get this message:
`UNKNOWN: Can't connect to data source 'DBI:oracle' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set) at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/dbi.pm line 210 `

Thank you
Best regards

**Comment by Sims24** [comment]
Hi, 

Yes you need to install perl-DBD-Oracle libraries and also the oracle-instantclient rpm available on Oracle site.

Thanks

**Comment by boogaaloo** [comment]
Thank you !
and for others? mysql and mssql?

**Comment by Sims24** [comment]
respectively : perl-DBD-MySQL and perl-DBD-Sybase + freetds compatibility v8.0 in freetds.conf

**Comment by boogaaloo** [comment]
Thank you very much

**Comment by Sims24** [comment]
you're welcome

**Comment by Sims24** [comment]
note: you should be able to track mssql and mysql dependencies automatically if you use centreon-plugin* packages available on centreon 3.4 standard repositories

**Comment by sboulianne** [comment]
# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=database::mysql::plugin --mode=connection-time --datasource=/var/lib/mysql
UNKNOWN: Can't connect to data source 'DBI:/var/lib/mysql' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set) at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/dbi.pm line 210. 

Same for database::oracle::plugin.
DBD::Oracle, DBD::mysql is installed.

**Comment by sboulianne** [comment]
Hello, 

La "datasource" au sens DBI n'est pas lié au "datadir" mysql.

Il faut utiliser cela comme ceci : 

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=database::mysql::plugin --mode=connection-time --host=X.X.X.X --username toto --password tata 

Merci, cela fonctionnel nikel.
